{"name": "Проверяем что выводится ошибка при удалении курьера не указав id", "status": "passed", "steps": [{"name": "Удаляем курьера по id", "status": "passed", "parameters": [{"name": "courier_id", "value": "''"}], "start": 1734183787447, "stop": 1734183787591}], "start": 1734183787447, "stop": 1734183787591, "uuid": "1ef24cd0-cbab-48b1-b243-9d434ab3a02d", "historyId": "a265a419490b6cfe1f636d4d00ca45d9", "testCaseId": "a265a419490b6cfe1f636d4d00ca45d9", "fullName": "tests.tests_courier.test_courier_delete.TestDeleteCourier#test_delete_courier_without_id", "labels": [{"name": "parentSuite", "value": "tests.tests_courier"}, {"name": "suite", "value": "test_courier_delete"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "172.31.52.44-vpn.dhcp.yndx.net"}, {"name": "thread", "value": "18098-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_courier.test_courier_delete"}]}