{"name": "Проверяем что выводится ошибка при удалении курьера указав несуществующий id", "status": "passed", "steps": [{"name": "Удаляем курьера по id", "status": "passed", "parameters": [{"name": "courier_id", "value": "1242423243"}], "start": 1734183787594, "stop": 1734183787736}], "start": 1734183787594, "stop": 1734183787737, "uuid": "badb4f60-0271-4092-a9bb-d59b1303768d", "historyId": "0edafb03e5a95853bae9c5ccdcca6ed3", "testCaseId": "0edafb03e5a95853bae9c5ccdcca6ed3", "fullName": "tests.tests_courier.test_courier_delete.TestDeleteCourier#test_delete_courier_with_non_existent_id", "labels": [{"name": "parentSuite", "value": "tests.tests_courier"}, {"name": "suite", "value": "test_courier_delete"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "172.31.52.44-vpn.dhcp.yndx.net"}, {"name": "thread", "value": "18098-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_courier.test_courier_delete"}]}